# Generated by Django 4.0 on 2021-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0002_mapbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosten',
            name='pauschal',
            field=models.CharField(default=0, max_length=30, null=0),
        ),
        migrations.AddField(
            model_name='mapbox',
            name='email',
            field=models.CharField(default=0, max_length=100, null=0),
        ),
        migrations.AddField(
            model_name='mapbox',
            name='password',
            field=models.CharField(default=0, max_length=100, null=0),
        ),
        migrations.AlterField(
            model_name='kosten',
            name='price',
            field=models.CharField(default=0, max_length=30, null=0),
        ),
    ]
